### ISSUE TITLE
Support for smart relay controllers is required.

### ISSUE THREAD

**Issue by lime0211** [chazepps/homebridge-hejhome#1]
https://hej.life/product/%EC%8A%A4%EB%A7%88%ED%8A%B8-%EB%A6%B4%EB%A0%88%EC%9D%B4-%EC%BB%A8%ED%8A%B8%EB%A1%A4%EB%9F%AC/109/category/63/

Above is the link to the product. I'm really happy if this is supported.

**Comment by chazepps** [comment]
@lime0211 관심 가져주셔서 고맙습니다 🤠

제가 구매해서 만들어볼게요 ;-)

**Comment by chazepps** [comment]
@lime0211 오늘 장비가 도착해서, `v1.0.3-alpha.1` 버전부터 기능이 추가되었습니다.
사용해보시고 이슈가 없으면, 다음 정식 버전에 배포할게요. 감사합니다! ☺️

**Comment by chazepps** [comment]
@lime0211 v1.1.0부터 [스마트 릴레이 컨트롤러](https://hej.life/product/detail.html?product_no=109)를 사용하실 수 있습니다.

The Smart Relay Controller is available starting from version v1.1.0.

**Comment by lime0211** [comment]
헉 감사합니다!

**Comment by lime0211** [comment]
안녕하세요,  개발자님
최초의 버전 부터 현재 버전인 1.1.0 업그레이드를 한 이후에도

[11/18/2024, 12:05:29 AM] [Hejhome] Token refreshed successfully
[11/18/2024, 12:05:30 AM] [Hejhome] mqtt subscribe onSuccess
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at hejRequest
***@***.***/homebridge-hejhome/src/requests/request.ts:26:17)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at
***@***.***/homebridge-hejhome/src/requests/realtime.ts:109:24
[11/18/2024, 12:05:30 AM] [Hejhome] Child bridge process ended
[11/18/2024, 12:05:30 AM] [Hejhome] Process Ended. Code: 1, Signal: null

위와 같이 실패하는 것으로 보입니다.

플러그인을 사용하기위해서 변경하여야하는것이 무엇인가요?

2024년 11월 17일 (일) 오전 8:42, Chaz Lee ***@***.***>님이 작성:

**Comment by lime0211** [comment]
1. 웹용 헤이홈에서 로그인 잘됩니다.

2. 확인해보니 홈서버설치된 PC에서 ping mqtt.hej.so 패킷 소실됩니다.

>mqtt.hej.so 접속이 가능하게 될려면 어떤처리를 해야할까요?
외부와 인터넷은 전부 잘되고있는중입니다.

3.현재 환경은
OS : Ubuntu Focal (20.04.5 LTS)
 Node.js 버전 : v22.11.0
이며 특이사항으로는 하이퍼V의 가상머신으로 실행중인 홈브릿지입니다.

4. 이전 버전부터 쭉 같은 오류입니다.

2024년 11월 20일 (수) 18:26, Chaz Lee ***@***.***>님이 작성:

**Comment by chazepps** [comment]
@lime0211 앗, 제가 네트워크 테스트 방법을 잘못 알려드렸습니다. 죄송합니다.

1. 해당 Windows 머신에서 Edge나 Chrome으로 https://square.hej.so/ 사이트를 접속해보세요. 장비가 웹사이트를 통해서 정상적으로 컨트롤 되는지 봐주세요. 그리고 나서 Homebridge를 Restart > iOS Home App > 장비를 조작해보세요. 

2. 혹시 가상머신에 GUI가 있다면, 위 페이지를 한번 시험해보세요.
homebridge-hejhome는 위 사이트의 패킷을 모방해서 서비스를 구현했습니다.
해서, 위 사이트도 마찬가지로 동작하지 않는다면... 디버깅이 좀 필요할 것 같습니다.

저는 Raspberry Pi 5에 Ubuntu를 설치해서 사용중입니다. 개발 환경은 macOS이구요.

제가 지금 Window 머신이 없어서 완전 같은 환경을 만들지는 못합니다.
다만, macOS에서 가상머신의 환경에서는 정상동작합니다. 특별히 OS 이슈는 아닐거라 생각되구요.

3. 정확한 테스트 방법은 이렇습니다.
```chaz@dev ~ % telnet mqtt.hej.so 1883
Trying 20.194.38.48...
Connected to masterrabbitmqd5swrzygrtoji-vm0.koreacentral.cloudapp.azure.com.
Escape character is '^]'.
```
4. 혹시 2가 동작하지 않는다면, 사용중인 환경에 외부로나가는 방화벽의 rule중에 1883이 닫혀있는지 확인해주세요.

---

일단 이렇게 한번 체크해주시고, 안되시면 잠깐 zoom 어떠세요? 직접 봐드리고 싶습니다!

**Comment by lime0211** [comment]
하필 오늘 저녁일이있어서 , 내일 한번 확인해보고 바로 알려드릴게요.

2024년 11월 21일 (목) 23:20, Chaz Lee ***@***.***>님이 작성:

**Comment by lime0211** [comment]
@chazepps  

1.웹용 헤이홈에서는 정상적으로 컨트롤 됩니다. 

2.현재 구성을 확인해보니 가상머신 > 도커 컨테이너 형태로 되어있는것으로 보이며
컨테이너 안에 우분투, 홈브릿지가 들어있는 상태로 보입니다. 
GUI도 없기때문에 잘모르겠습니다.

3.telnet으로 해당 아이피 접속은 되는데, ping은 안되네요.

4.잘은 모르지만 iptables 확인 해보면 모든 포트가 개방된 상태로 보입니다.


--------
오늘 내일은 특별한 일이없기 때문에 언제든 괜찮습니다.

**Comment by lime0211** [comment]
라즈베리파이5를 주문했습니다.. 설정후에 다시 알려드릴게요  :)

**Comment by chazepps** [comment]
@lime0211 헉 그렇군요ㅠ

제가 처음에 네트워크 확인 방법을 잘못 알려드렸습니다.
hejhome의 서버측에서 ping을 안받는걸로 보여요. ping은 안되는게 정상으로 보입니다. 

사실 PC에서는 방화벽이 일반적으로 없을 것 같고, 컨테이너 환경이라고 특별히 다를것 같지는 않아보여요.
제가 Github 노티를 자주 놓쳐서 회신이 늦네요 🥲

**Comment by chazepps** [comment]
v1.1.1 에서 개선되었습니다.

방이 2개이상 구성된 계정에서, 디바이스가 0개인 방이 있는 경우 오류가 있었습니다.
